{
 "title": "RIG",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"reactive-interaction-gateway\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{container=\"reactive-interaction-gateway\"}[5m])"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rig_proxy_requests_total[30s])*20"
    }
   ]
  },
  { "title": "Total numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "HTTP target",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rig_proxy_requests_total{target=\"http\"})"
    }
   ]
  },
  {
   "title": "Kafka target",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rig_proxy_requests_total{target=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Register POST Async",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rig_proxy_requests_total{method=\"POST\",path=\"/api/rs/register\"})"
    }
   ]
  },
  {
   "title": "Register POST Sync",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rig_proxy_requests_total{method=\"POST\",path=\"/api/rs/register/sync\"})"
    }
   ]
  },
  {
   "title": "All HTTP requests",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(rig_proxy_requests_total)" }
   ]
  },
  {
   "title": "HTTP Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rig_proxy_requests_total{status=\"ok\"})/sum(rig_proxy_requests_total))"
    }
   ]
  },
  {
   "title": "Kafka POST",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rig_proxy_requests_total{method=\"POST\",path=\"/api/kafka\"})"
    }
   ]
  }
 ]
}