replicaCount: 1

image:
  repository: openslava-2019-rig-example_notification-service
  tag: latest
  pullPolicy: Never # needed for local Kubernetes cluster (docker desktop)

service:
  port: 6000
  targetPort: 6000
  type: ClusterIP

deployment:
  port: 6000
  env:
    KAFKA_BROKERS: kafka:9092
