replicaCount: 1

image:
  repository: openslava-rig_registration-service
  tag: latest
  pullPolicy: Never # needed for local Kubernetes cluster (docker desktop)

service:
  port: 5000
  targetPort: 5000
  type: ClusterIP

deployment:
  port: 5000
  env:
    KAFKA_BROKERS: kafka:9092
