# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: openslava-2019-rig-example_frontend
  tag: latest
  pullPolicy: Never

service:
  port: 9090
  targetPort: 80
  type: ClusterIP

deployment:
  port: 80
