replicaCount: 1

image:
  repository: accenture/reactive-interaction-gateway
  tag: latest
  pullPolicy: Always

apiPort: 4010
inboundPort: 4000

service:
  type: LoadBalancer

service_headless:
  type: ClusterIP
  clusterIP: None

deployment:
  env:
    DISCOVERY_TYPE: dns
    DNS_NAME: reactive-interaction-gateway-headless.default.svc.cluster.local
    NODE_COOKIE: openslava
    LOG_LEVEL: debug
    KAFKA_BROKERS: kafka:9092
    KAFKA_SOURCE_TOPICS: openslava
    PROXY_KAFKA_REQUEST_TOPIC: openslava
    PROXY_KAFKA_RESPONSE_TOPICS: openslava
    API_HTTP_PORT: 4010
    INBOUND_PORT: 4000
    PROXY_CONFIG_FILE: '[{"id":"registration-service","name":"registration-service","auth_type":"none","auth":{"use_header":false,"header_name":"","use_query":false,"query_name":""},"versioned":false,"version_data":{"default":{"endpoints":[{"id":"register","path":"/api/rs/register","method":"POST","secured":false},{"id":"register-sync","path":"/api/rs/register/sync","path_replacement":"/api/rs/register","method":"POST","secured":false,"response_from":"kafka"}]}},"proxy":{"use_env":true,"target_url":"RS_HOST","port":5000}},{"id":"kafka-service","name":"kafka-service","auth_type":"none","auth":{"use_header":false,"header_name":"","use_query":false,"query_name":""},"versioned":false,"version_data":{"default":{"endpoints":[{"id":"kafka","path":"/api/kafka","method":"POST","target":"kafka","secured":false}]}},"proxy":{"use_env":true,"target_url":"KAFKA_HOST","port":9092}}]'
    RS_HOST: registration-service
    KAFKA_HOST: kafka
    EXTRACTORS: '{"com.openslava.reg.confirmed":{"name":{"stable_field_index":0,"event":{"json_pointer":"/data/name"}}}}'
